function neolan1neosp1 = importblast(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NEOLAN1NEOSP1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  NEOLAN1NEOSP1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  neolan1neosp1 = importfile("/Users/nabilalansari/Desktop/LTRs/neolan1_neosp1.txt", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 21-Mar-2024 19:13:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["scaffold_1_dbseqnr_0_2029421737", "scaffold_13_dbseqnr_12_292269293713", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["scaffold_1_dbseqnr_0_2029421737", "scaffold_13_dbseqnr_12_292269293713", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["scaffold_1_dbseqnr_0_2029421737", "scaffold_13_dbseqnr_12_292269293713", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"], "EmptyFieldRule", "auto");

% Import the data
neolan1neosp1 = readmatrix(filename, opts);

end