function predneosp1unmasked90 = importltrname(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  PREDNEOSP1UNMASKED90 = IMPORTFILE3(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  PREDNEOSP1UNMASKED90 = IMPORTFILE3(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  predneosp1unmasked90 = importfile3("/Users/nabilalansari/Desktop/LTRHarvest 90% Vmatch 95%/pred-neosp1unmasked90.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Sep-2022 18:49:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ">";

% Specify column names and types
opts.VariableNames = ["Var1", "scaffold_1dbseqnr02029421737"];
opts.SelectedVariableNames = "scaffold_1dbseqnr02029421737";
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "scaffold_1dbseqnr02029421737"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "scaffold_1dbseqnr02029421737"], "EmptyFieldRule", "auto");

% Import the data
predneosp1unmasked90 = readtable(filename, opts);

end