function ltrdataneosp1 = importltrlength(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  LTRDATANEOSP1 = IMPORTFILE3(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  LTRDATANEOSP1 = IMPORTFILE3(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ltrdataneosp1 = importfile3("/Users/nabilalansari/Desktop/bar code for genomes/ltrdata_neosp1.txt", [14, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Feb-2023 13:21:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [14, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "gt", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "gt";
opts.VariableTypes = ["string", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
ltrdataneosp1 = readtable(filename, opts);

%% Convert to output type
ltrdataneosp1 = table2array(ltrdataneosp1);
end