function t0results = importdeseqrest30(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  T0RESULTS = IMPORTFILE3(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  T0RESULTS = IMPORTFILE3(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  t0results = importfile3("/Users/nabilalansari/Desktop/Research/June 3/heatshock new fx (outdated now)/t0results.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Jun-2023 20:21:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Transcriptome", "meanExp_t30", "log2FC_t30", "Var4", "Var5", "Var6", "FDR_t30"];
opts.SelectedVariableNames = ["Transcriptome", "meanExp_t30", "log2FC_t30", "FDR_t30"];
opts.VariableTypes = ["string", "double", "double", "string", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Transcriptome", "Var4", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Transcriptome", "Var4", "Var5", "Var6"], "EmptyFieldRule", "auto");

% Import the data
t0results = readtable(filename, opts);

end