function f = importdata_promoters(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SHORTENEDQUERYPROMOTERDBNEOSP1 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  SHORTENEDQUERYPROMOTERDBNEOSP1 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  shortenedquerypromoterdbneosp1 = importfile("/Users/nabilalansari/Desktop/Research/March 28 2024/All LTRs from LTRHarvest/neosp1/shortened_querypromoter_dbneosp1.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Mar-2024 16:15:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Promoter", "LTR", "PercentIdentity", "SeqLength", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Score"];
opts.SelectedVariableNames = ["Promoter", "LTR", "PercentIdentity", "SeqLength", "Score"];
opts.VariableTypes = ["double", "string", "double", "double", "string", "string", "string", "string", "string", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["LTR", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["LTR", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
f = readtable(filename, opts);

end