function G1heatshockrawexpectedcountsWithB3 = importheatshockrawdata(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  G1HEATSHOCKRAWEXPECTEDCOUNTSWITHB3 = IMPORTFILE3(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  G1HEATSHOCKRAWEXPECTEDCOUNTSWITHB3 = IMPORTFILE3(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  G1heatshockrawexpectedcountsWithB3 = importfile3("/Users/nabilalansari/Desktop/Research/june 18/Genomes/neosp1/G1_heatshock_raw_expectedcountsWithB3.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jun-2023 20:16:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "B1", "B2", "B3", "B4", "t0R1", "t0R2", "t0R3", "t0R4", "t15R1", "t15R2", "t15R3", "t15R4", "t30R1", "t30R2", "t30R3", "t45R2", "t45R3", "t45R4", "t60R1", "t60R3", "t60R4"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");

% Import the data
G1heatshockrawexpectedcountsWithB3 = readtable(filename, opts);

end