function classifiedltrs = importtesorter(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  CLASSIFIEDLTRS = IMPORTFILE3(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CLASSIFIEDLTRS = IMPORTFILE3(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  classifiedltrs = importfile3("/Users/nabilalansari/Desktop/code 70% coverage/classifiedltrs.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Sep-2022 23:19:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TE", "Var2", "Superfamily", "Var4", "Var5", "Var6", "Domains"];
opts.SelectedVariableNames = ["TE", "Superfamily", "Domains"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["TE", "Var2", "Superfamily", "Var4", "Var5", "Var6", "Domains"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["TE", "Var2", "Superfamily", "Var4", "Var5", "Var6", "Domains"], "EmptyFieldRule", "auto");

% Import the data
classifiedltrs = readtable(filename, opts);

end