function cov90identdbltrquerytranscriptomeG1 = importrpkm(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  COV90IDENTDBLTRQUERYTRANSCRIPTOMEG1 = IMPORTFILE3(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  COV90IDENTDBLTRQUERYTRANSCRIPTOMEG1 = IMPORTFILE3(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  cov90identdbltrquerytranscriptomeG1 = importfile3("/Users/nabilalansari/Desktop/Research/april 16 tasks/code final/neosp1/70cov90ident_dbltrquerytranscriptome_G1.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Apr-2023 22:09:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", "rpkm"];

% Specify column names and types
opts.VariableNames = ["Var1", "rpkm", "LTRName", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"];
opts.SelectedVariableNames = ["rpkm", "LTRName"];
opts.VariableTypes = ["string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "LTRName", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "LTRName", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"], "EmptyFieldRule", "auto");

% Import the data
cov90identdbltrquerytranscriptomeG1 = readtable(filename, opts);

end