function cov90identdbltrquerytranscriptomeG1 = importdatablast(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  COV90IDENTDBLTRQUERYTRANSCRIPTOMEG1 = IMPORTFILE3(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  COV90IDENTDBLTRQUERYTRANSCRIPTOMEG1 = IMPORTFILE3(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  cov90identdbltrquerytranscriptomeG1 = importfile3("/Users/nabilalansari/Desktop/Research/May 11/Code Final/neosp1/70cov90ident_dbltrquerytranscriptome_G1.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-May-2023 21:39:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Transcriptome", "LTRName", "AlignmentPercentIdentity", "AlignmentLength", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"];
opts.SelectedVariableNames = ["Transcriptome", "LTRName", "AlignmentPercentIdentity", "AlignmentLength"];
opts.VariableTypes = ["string", "string", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Transcriptome", "LTRName", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Transcriptome", "LTRName", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12"], "EmptyFieldRule", "auto");

% Import the data
cov90identdbltrquerytranscriptomeG1 = readtable(filename, opts);

end